var cards = 
[
	[
		"Dining Table",
		"Writing Pen",
		"Umbrella",
		"Hair Brush",
		"Bicycle",
		"Picnic rug",
		"Waterproof Coat",
		"Rubbish Bin",
		"Fork",
		"Analogue Clock",

	],
	[
		"At home",
		"At the gym",
		"In the office",
		"On the street",
		"At the shopping mall",
		"At the doctor surgery",
		"In the park",
		"At the airport",
		"On the train",
	],
	[
		"A Family",
		"2 or more Strangers",
		"Friends",
		"Children",
		"Retired Person",
		"Student",
		"New Parent",
		"Graduate",
		"Immigrant",
		"Tourist", 
		"Someone Walking a Dog",
		"Cyclist",
	],
	[
		[
			"Captivation",
			"Challenge",
			"Competition",
			"Completion",
			"Control",
			"Discovery",
			"Eroticism",
			"Exploration",
			"Expression",
			"Fantasy",
			"Fellowship",
			"Humor",
			"Nurture",
			"Relaxation",
			"Sensation",
			"Simulation",
			"Submission",
			"Subversion",
			"Sympathy",
			"Thrill"
		],
		[
			"Forgetting one’s surroundings",
			"Testing abilities in a demanding task",
			"Contest with oneself or an opponent",
			"Finishing a major task, closure",
			"Commanding, regulating, acting autonomously",
			"Finding something new or unknown",
			"A sexually arousing experience",
			"Investigating an object or situation",
			"Manifesting oneself creatively",
			"An imagined experience",
			"Friendship, communality, or intimacy",
			"Fun, joy, amusement, jokes, gags",
			"Taking care of oneself or others",
			"Relief from bodily or mental work",
			"Excitement by stimulating senses",
			"An imitation of everyday life",
			"Being part of a larger structure, team or organisation",
			"Breaking social rules and norms",
			"Sharing emotional feelings",
			"Excitement derived from risk, danger"
		]
	],
]